### ISSUE TITLE
One that is missing

### ISSUE THREAD

**Issue by RockyZuo2023** [Chuan-10/awesome-language-embedded-3D-representations#1]
https://arxiv.org/abs/2401.01970
FMGS: Foundation Model Embedded 3D Gaussian Splatting for Holistic 3D Scene Understanding

**Comment by Chuan-10** [comment]
Thank you, I have added it!

**Comment by ZuoJiaxing** [comment]
FMGS is accepted by IJCV 2024. Please update it, thanks!

**Comment by Chuan-10** [comment]
Thank you, I will update it.
